nelmio_api_doc:
    documentation:
        info:
            title: Naar school in vlaanderen
            description: Gegevens API
            version: 1.0.0
        components:
            securitySchemes:
                ApiKeyAuth:
                    type: apiKey
                    in: header
                    name: X-AUTH-TOKEN
        security:
            - ApiKeyAuth: []
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
